import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.system": "The System",
    "nav.about": "About",
    "nav.plans": "Plans",
    "nav.catalog": "Services",
    "nav.contact": "Contact",
    "nav.bookCall": "Book a Call",
    "nav.join": "Join Now",

    // Hero
    "hero.badge": "Execution System for Visibility",
    "hero.headline": "You Don't Need Fame.",
    "hero.headline2": "You Need a System.",
    "hero.subheadline": "Join VISION DM and publish videos monthly with a simple, repeatable content system. No talent required. Just execution.",
    "hero.cta1": "Join the System",
    "hero.cta2": "Book a Call",
    "hero.stat1": "Monthly Tasks",
    "hero.stat2": "Seconds/Video",
    "hero.stat3": "Levels",

    // Problem
    "problem.label": "The Problem",
    "problem.headline": "The Problem Is Not Talent,",
    "problem.headline2": "It's Not Understanding the Power of Social Media",
    "problem.intro": "The truth is brutal but simple:",
    "problem.point1.title": "They overthink everything",
    "problem.point1.desc": "Paralysis by analysis. Waiting for the perfect moment that never comes.",
    "problem.point2.title": "They don't post consistently",
    "problem.point2.desc": "One video today, nothing for weeks. The algorithm forgets you exist.",
    "problem.point3.title": "They have no system",
    "problem.point3.desc": "Random ideas, random execution, random results. Hope is not a strategy.",
    "problem.point4.title": "They depend on motivation",
    "problem.point4.desc": "Motivation is temporary. Discipline and structure are permanent.",

    // Solution
    "solution.label": "The DM System",
    "solution.formula": "Simple + Structured + Executable = Visualization",
    "solution.headline": "Simple. Structured.",
    "solution.headline2": "Executable.",
    "solution.intro": "Our methodology eliminates complexity. You receive clear tasks. You execute. We handle the rest.",
    "solution.step": "Step",
    "solution.step0.title": "Fill Your Brand Form",
    "solution.step0.desc": "Complete a form about your niche and personality to build your unique brand identity.",
    "solution.step1.title": "Receive All Your Tasks",
    "solution.step1.desc": "Structured tasks delivered to your folder based on your plan level.",
    "solution.step2.title": "Record Your Weekly Tasks",
    "solution.step2.desc": "5-20 second videos. Simple prompts. Quick execution.",
    "solution.step3.title": "We Edit, Publish & You Grow",
    "solution.step3.desc": "We schedule your content a week in advance, ensuring total videos uploaded plus the consistency needed for real results.",
    "solution.result": "This is math. These are probabilities. More videos, more chances—with video equations of just seconds.",

    // Video
    "video.label": "Methodology",
    "video.headline": "Understand the",
    "video.headline2": "Visualization System",
    "video.description": "Alejandro Mora explains why short-form content, consistency, and execution beat talent every time.",
    "video.placeholder": "Video Coming Soon",

    // Who
    "who.label": "Who Is This For",
    "who.headline": "Built for Executors,",
    "who.headline2": "Not Dreamers",
    "who.entrepreneur": "Entrepreneurs",
    "who.business": "Business Owners",
    "who.creator": "Content Creators",
    "who.artist": "Artists & Musicians",
    "who.local": "Local Businesses",
    "who.anyone": "Anyone Ready to Execute",
    "who.warning": "This is NOT for people looking for shortcuts, magic formulas, or overnight success. If you're not ready to execute, this is not for you.",

    // Founder / About Us
    "founder.label": "About Us",
    "founder.headline": "Our Mission",
    "founder.headline2": "& Vision",
    
    // Mission
    "founder.mission.label": "Our Mission",
    "founder.mission.title": "Building Real Visibility Systems",
    "founder.mission.text": "At VISION DM, we build real visibility systems for entrepreneurs, creators, and businesses ready to execute. Our mission is to turn ideas into impact, consistency into growth, and content into measurable results — without hype, shortcuts, or empty promises. We don't sell fame. We build systems that work.",
    
    // Vision
    "founder.vision.label": "Our Vision",
    "founder.vision.title": "Infrastructure for Growth",
    "founder.vision.text": "Our vision is to become a global growth ecosystem powered by structure, execution, and clarity. We aim to give people around the world a reliable way to scale their brand, reach, and revenue through a system that is simple, repeatable, and data-driven. VISION DM is not a traditional agency. It's infrastructure for growth.",
    
    // Founder Profile
    "founder.role": "Founder & System Architect",
    "founder.name": "Daniel Alejandro Mora",
    "founder.title": "Colombian Entrepreneur, Streamer & Founder of the DM System",
    "founder.bio": "More than 10 years of process not just building businesses, but observing people, patterns, and real behaviors. Each stage—from starting young, failing, migrating, starting from zero, and creating again—strengthened a single competitive advantage: the ability to think clearly, read contexts, and turn ideas into executable systems.",
    "founder.bio2": "True power doesn't lie in talent or luck, but in a mind that knows how to create, adapt, and repeat what works. From that accumulation of real experiences, the DM System was born: a methodology designed to transform intention into visibility, and visibility into measurable growth.",
    
    "founder.trust1": "Registered US Company",
    "founder.trust2": "Real Identity & Transparency",
    "founder.trust3": "Proven Methodology",
    "founder.instagram": "Connect",
    "founder.cta.book": "Book a Call",

    // Plans
    "plans.label": "Membership",
    "plans.headline": "Choose Your",
    "plans.headline2": "Growth Level",
    "plans.intro": "Structured systems. Real execution. Consistent visibility.",
    "plans.level1": "Nivel 1",
    "plans.level1.subtitle": "Base",
    "plans.level1.desc": "Start with consistency and a solid foundation",
    "plans.level2": "Nivel 2",
    "plans.level2.subtitle": "Growth",
    "plans.level2.desc": "Grow with tracking and continuous improvement",
    "plans.level3": "Nivel 3",
    "plans.level3.subtitle": "Scale",
    "plans.level3.desc": "Control, clarity and sustained growth",
    "plans.level3.metric.ideas": "content ideas",
    "plans.level3.platforms": "Facebook, Instagram, TikTok, YouTube",
    "plans.level3.feature.profile": "Deep profile and brand analysis",
    "plans.level3.feature.positioning": "Clear strategic positioning",
    "plans.level3.feature.dataDriven": "Data and behavior-driven execution",
    "plans.level3.feature.dmSystem": "Personalized DM system at scale",
    "plans.level3.feature.ideas": "100 monthly ideas with strategic intent",
    "plans.level3.feature.indirectSales": "Indirect selling (no commercial pressure)",
    "plans.level3.feature.organization": "Professional content organization",
    "plans.level3.feature.designResources": "30 premium graphic design resources",
    "plans.level3.feature.nicheAnalysis": "Advanced niche & trends analysis",
    "plans.level3.feature.prioritySupport": "Priority support",
    "plans.level3.feature.weeklySessions": "Weekly strategy sessions",
    "plans.level3.feature.optimization": "Continuous system optimization",
    "plans.cta": "Get Started",
    "plans.feature.tasks": "monthly structured tasks",
    "plans.feature.videos": "base videos (max 20s)",
    "plans.feature.publications": "monthly publications",
    "plans.feature.networks": "Facebook & Instagram",
    "plans.feature.logo.professional": "Professional logo design",
    "plans.feature.logo.premium": "Premium logo design",
    "plans.feature.logo.brandkit": "Complete brand kit",
    "plans.feature.cover": "Social media resources",
    "plans.feature.folder": "Organized content folder",
    "plans.feature.support.weekday": "Business hours support",
    "plans.feature.support.24": "24/7 priority support",
    "plans.feature.controls": "monthly personalized reviews",
    "plans.feature.strategy.monthly": "Monthly strategy session",
    "plans.feature.strategy.weekly": "Weekly strategy sessions",
    "plans.feature.profile.analysis": "Deep profile analysis to identify your vision",
    "plans.feature.design.resources.15": "15 additional graphic design resources",
    "plans.feature.design.resources.30": "30 additional graphic design resources",
    "plans.feature.niche.analysis": "Pro niche & trends analysis",
    "plans.popular": "Most Popular",
    "plans.ideal": "Ideal for",
    "plans.platforms.label": "Platforms",

    // Booking
    "booking.label": "Let's Talk",
    "booking.headline": "Book a Personal",
    "booking.headline2": "Strategy Call",
    "booking.description": "Have questions? Want to discuss if this is right for you? Schedule a call with our team. No pressure, no sales tricks—just honest conversation.",
    "booking.cta": "Schedule Your Call",
    "booking.note": "Calls are for serious inquiries only",

    // CTA
    "cta.headline": "Stop Waiting.",
    "cta.headline2": "Start Executing.",
    "cta.description": "Visibility creates opportunity. Opportunity creates legacy. The only thing between you and results is execution.",
    "cta.button": "Join VISION DM",
    "cta.secondary": "Start Executing Today",

    // Footer
    "footer.tagline": "Visibility. Execution. Legacy.",
    "footer.rights": "All rights reserved.",
    "footer.company": "VISION DM LLC",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.social": "Social",
    "footer.contact": "Contact",

    // Privacy Policy
    "privacy.title": "Privacy",
    "privacy.title2": "Policy",
    "privacy.updated": "Last updated: January 30, 2026",
    "privacy.intro": "At Vision DM LLC (\"Vision DM\", \"we\"), we respect your privacy. This Policy explains how we collect, use, and protect your information when you visit our website, use our services, or communicate with us.",
    "privacy.s1.title": "1. Information We Collect",
    "privacy.s1.intro": "We may collect:",
    "privacy.s1.a.title": "a) Information you provide to us",
    "privacy.s1.a.item1": "First and last name",
    "privacy.s1.a.item2": "Email and/or phone number",
    "privacy.s1.a.item3": "Billing information (if applicable)",
    "privacy.s1.a.item4": "Messages and content you send (forms, chats, requests, creative briefs)",
    "privacy.s1.b.title": "b) Automatically collected information",
    "privacy.s1.b.item1": "Approximate IP address, browser type, device, operating system",
    "privacy.s1.b.item2": "Pages visited, browsing time, links and events (analytics)",
    "privacy.s1.b.item3": "Cookies and similar technologies (see section 6)",
    "privacy.s1.c.title": "c) Third-party information (if applicable)",
    "privacy.s1.c.text": "Payment processors, scheduling platforms, marketing or analytics tools, social networks when you interact with our profiles or ads.",
    "privacy.s2.title": "2. How We Use Your Information",
    "privacy.s2.intro": "We use your information to:",
    "privacy.s2.item1": "Respond to requests, quotes, and support",
    "privacy.s2.item2": "Provide and improve our services",
    "privacy.s2.item3": "Process payments and prevent fraud",
    "privacy.s2.item4": "Send communications (updates, confirmations, service changes)",
    "privacy.s2.item5": "Marketing (only when permitted by law or with your consent, as applicable)",
    "privacy.s2.item6": "Legal compliance and site security",
    "privacy.s3.title": "3. Legal Basis (if applicable)",
    "privacy.s3.intro": "Depending on your location, we process data based on:",
    "privacy.s3.item1": "Contract execution (service provision)",
    "privacy.s3.item2": "Legitimate interest (security, improvements, fraud prevention)",
    "privacy.s3.item3": "Consent (marketing, non-essential cookies)",
    "privacy.s3.item4": "Legal obligations (taxes, accounting)",
    "privacy.s4.title": "4. How We Share Your Information",
    "privacy.s4.noSell": "We do not sell your personal information.",
    "privacy.s4.intro": "We may share it with:",
    "privacy.s4.item1": "Vendors that help us operate (hosting, analytics, CRM, email, payments)",
    "privacy.s4.item2": "Authorities if required by law or to protect rights and security",
    "privacy.s4.item3": "Business transfers (merger, acquisition, reorganization)",
    "privacy.s4.note": "All vendors must handle information in accordance with this Policy and reasonable security measures.",
    "privacy.s5.title": "5. Data Retention",
    "privacy.s5.intro": "We retain information only as long as necessary to:",
    "privacy.s5.item1": "Provide the service",
    "privacy.s5.item2": "Comply with legal/accounting obligations",
    "privacy.s5.item3": "Resolve disputes and enforce agreements",
    "privacy.s6.title": "6. Cookies and Similar Technologies",
    "privacy.s6.intro": "We use cookies for:",
    "privacy.s6.item1": "Site functionality",
    "privacy.s6.item2": "Analytics and performance",
    "privacy.s6.item3": "Marketing (if applicable)",
    "privacy.s6.note": "You can control cookies from your browser settings.",
    "privacy.s7.title": "7. Security",
    "privacy.s7.text": "We implement reasonable measures (technical and organizational) to protect your information. However, no system is 100% secure.",
    "privacy.s8.title": "8. Your Rights and Choices",
    "privacy.s8.intro": "Depending on your state/country, you may have the right to:",
    "privacy.s8.item1": "Access, correct, or delete your information",
    "privacy.s8.item2": "Object to or limit certain uses",
    "privacy.s8.item3": "Withdraw consent (when applicable)",
    "privacy.s8.contact": "To exercise rights:",
    "privacy.s9.title": "9. Children's Privacy",
    "privacy.s9.text": "Our services are not directed to children under 13 years old (or the applicable minimum age). If you believe a minor has sent us data, contact us to delete it.",
    "privacy.s10.title": "10. Third-Party Links",
    "privacy.s10.text": "Our site may contain links to third parties. We do not control their policies. Review each site's privacy policy.",
    "privacy.s11.title": "11. Changes to This Policy",
    "privacy.s11.text": "We may update this Policy. We will post the new \"Last updated\" date. Significant changes may be communicated by email if applicable.",
    "privacy.s12.title": "12. Contact",
    "privacy.s12.email": "Email:",

    // Terms of Service
    "terms.title": "Terms of",
    "terms.title2": "Service",
    "terms.updated": "Last updated: January 30, 2026",
    "terms.intro": "These Terms of Service (\"Terms\") govern the use of the website and services offered by Vision DM LLC (\"Vision DM\", \"we\"). By accessing or using the site, you accept these Terms.",
    "terms.s1.title": "1. Eligibility",
    "terms.s1.text": "You must be at least 18 years old (or the age of majority in your jurisdiction) to use our services, or have authorization from a responsible adult.",
    "terms.s2.title": "2. Services",
    "terms.s2.text1": "We offer creative and digital services (for example: branding, design, editing, content, consulting, optimization, and related products), as published on the site or agreed in writing.",
    "terms.s2.text2": "The exact scope, deliverables, timelines, and prices are defined in:",
    "terms.s2.item1": "a proposal / quote,",
    "terms.s2.item2": "a contract, or",
    "terms.s2.item3": "a written agreement (includes email or project document).",
    "terms.s2.note": "If there is a conflict between these Terms and a specific contract, the specific contract prevails.",
    "terms.s3.title": "3. Payments and Billing",
    "terms.s3.item1": "Prices are shown in USD (unless otherwise indicated).",
    "terms.s3.item2": "Payments may be upfront, by milestones, or according to the agreed plan.",
    "terms.s3.item3": "If a payment is not made, we may pause deliveries and support until regularized.",
    "terms.s3.item4.label": "Third-party charges:",
    "terms.s3.item4.text": "Your bank or gateway may charge fees; we do not control them.",
    "terms.s4.title": "4. Refunds",
    "terms.s4.item1": "As these are creative and digital services, refunds are not automatic.",
    "terms.s4.item2": "If work has already started, payments may be non-refundable, in whole or in part, depending on progress and costs.",
    "terms.s4.item3": "If a refund or adjustment applies, it will be defined on a case-by-case basis according to the agreement.",
    "terms.s5.title": "5. Revisions and Scope Changes",
    "terms.s5.item1": "We include revision rounds per deliverable (if not defined by contract, we assume 1-2 reasonable rounds).",
    "terms.s5.item2": "Changes outside the original scope (\"scope creep\") may require extra cost or schedule adjustment.",
    "terms.s6.title": "6. Client Responsibilities",
    "terms.s6.intro": "To meet deadlines, the client must:",
    "terms.s6.item1": "Deliver necessary information and materials (logos, photos, access, brief, references)",
    "terms.s6.item2": "Respond in reasonable times",
    "terms.s6.item3": "Confirm approvals when requested",
    "terms.s6.note": "Client delays may move delivery dates.",
    "terms.s7.title": "7. Intellectual Property",
    "terms.s7.a.title": "a) Client Materials",
    "terms.s7.a.text": "Remain the client's property. You authorize us to use them only to complete the project.",
    "terms.s7.b.title": "b) Final Deliverables",
    "terms.s7.b.text": "Ownership/use of the final deliverable transfers to the client once full payment is received, unless the contract states otherwise.",
    "terms.s7.c.title": "c) Editable Files / Sources",
    "terms.s7.c.text": "Delivery of editable files (e.g., .PSD, .AI, projects) must be explicitly included in the agreement. If not, we may deliver final formats (PNG/JPG/MP4/PDF, etc.).",
    "terms.s7.d.title": "d) Portfolio",
    "terms.s7.d.text": "We may display the work in our portfolio/social media as a success case, unless the client requests confidentiality in writing or an NDA is agreed.",
    "terms.s8.title": "8. Site Use",
    "terms.s8.intro": "You agree not to:",
    "terms.s8.item1": "Use the site for illegal or fraudulent activities",
    "terms.s8.item2": "Attempt to access systems or accounts without authorization",
    "terms.s8.item3": "Copy or redistribute site content without permission",
    "terms.s9.title": "9. Disclaimers",
    "terms.s9.text": "The site and services are provided \"as is.\" We do not guarantee specific results (e.g., growth, sales, virality), as they depend on multiple factors outside our control (market, platform, budget, consistency, etc.).",
    "terms.s10.title": "10. Limitation of Liability",
    "terms.s10.intro": "To the extent permitted by law, Vision DM will not be liable for:",
    "terms.s10.item1": "Indirect, incidental, special, or consequential losses",
    "terms.s10.item2": "Lost profits, data loss, or reputation damage",
    "terms.s10.item3": "Third-party failures (platforms, hosting, social networks, gateways)",
    "terms.s10.note": "If liability applies, it is limited to the amount paid by the client in the last 90 days, or the specific project, whichever is less.",
    "terms.s11.title": "11. Termination",
    "terms.s11.intro": "We may terminate or suspend access/service if:",
    "terms.s11.item1": "There is payment default",
    "terms.s11.item2": "There is misuse of the site",
    "terms.s11.item3": "There is abuse, harassment, or inappropriate behavior",
    "terms.s11.note": "The client may also terminate according to the contract. Work completed to date is billed according to progress.",
    "terms.s12.title": "12. Governing Law",
    "terms.s12.text1": "These Terms are governed by the laws of the State of Utah, United States, without regard to conflicts of laws.",
    "terms.s12.text2": "Jurisdiction: Salt Lake City, Utah.",
    "terms.s13.title": "13. Changes to Terms",
    "terms.s13.text": "We may update the Terms. The \"Last updated\" date will indicate changes. Continued use of the site implies acceptance of the current version.",
    "terms.contact.title": "Contact",
    "terms.contact.email": "Email:",
  },
  es: {
    // Header
    "nav.system": "El Sistema",
    "nav.about": "Nosotros",
    "nav.plans": "Planes",
    "nav.catalog": "Servicios",
    "nav.contact": "Contacto",
    "nav.bookCall": "Agendar Llamada",
    "nav.join": "Únete Ahora",

    // Hero
    "hero.badge": "Sistema de Ejecución para Visibilidad",
    "hero.headline": "No Necesitas Fama.",
    "hero.headline2": "Necesitas un Sistema.",
    "hero.subheadline": "Únete a VISION DM y publica videos mensuales con un sistema de contenido simple y repetible. No se requiere talento. Solo ejecución.",
    "hero.cta1": "Únete al Sistema",
    "hero.cta2": "Agendar Llamada",
    "hero.stat1": "Tareas Mensuales",
    "hero.stat2": "Segundos/Video",
    "hero.stat3": "Niveles",

    // Problem
    "problem.label": "El Problema",
    "problem.headline": "El Problema No Es el Talento,",
    "problem.headline2": "Es No Entender el Poder de las Redes Sociales",
    "problem.intro": "La verdad es brutal pero simple:",
    "problem.point1.title": "Piensan demasiado",
    "problem.point1.desc": "Parálisis por análisis. Esperando el momento perfecto que nunca llega.",
    "problem.point2.title": "No publican consistentemente",
    "problem.point2.desc": "Un video hoy, nada por semanas. El algoritmo te olvida.",
    "problem.point3.title": "No tienen sistema",
    "problem.point3.desc": "Ideas random, ejecución random, resultados random. La esperanza no es estrategia.",
    "problem.point4.title": "Dependen de la motivación",
    "problem.point4.desc": "La motivación es temporal. La disciplina y estructura son permanentes.",

    // Solution
    "solution.label": "El Sistema DM",
    "solution.formula": "Simple + Estructurado + Ejecutable = Visualización",
    "solution.headline": "Simple. Estructurado.",
    "solution.headline2": "Ejecutable.",
    "solution.intro": "Nuestra metodología elimina la complejidad. Recibes tareas claras. Ejecutas. Nosotros hacemos el resto.",
    "solution.step": "Paso",
    "solution.step0.title": "Completa Tu Formulario",
    "solution.step0.desc": "Llena un formulario sobre tu nicho y personalidad para construir tu identidad de marca única.",
    "solution.step1.title": "Recibe Todas Tus Tareas",
    "solution.step1.desc": "Tareas estructuradas entregadas en tu carpeta según tu nivel de plan.",
    "solution.step2.title": "Graba Tus Tareas Semanales",
    "solution.step2.desc": "Videos de 5-20 segundos. Prompts simples. Ejecución rápida.",
    "solution.step3.title": "Editamos, Publicamos y Creces",
    "solution.step3.desc": "Programamos tu contenido una semana antes, asegurando el total de videos subidos más la consistencia necesaria para resultados reales.",
    "solution.result": "Esto es matemática. Son probabilidades. Más videos, más probabilidades—con ecuaciones de video de solo segundos.",

    // Video
    "video.label": "Metodología",
    "video.headline": "Entiende el",
    "video.headline2": "Sistema de Visualización",
    "video.description": "Alejandro Mora explica por qué el contenido corto, la consistencia y la ejecución superan al talento siempre.",
    "video.placeholder": "Video Próximamente",

    // Who
    "who.label": "Para Quién Es Esto",
    "who.headline": "Hecho para Ejecutores,",
    "who.headline2": "No Soñadores",
    "who.entrepreneur": "Emprendedores",
    "who.business": "Dueños de Negocios",
    "who.creator": "Creadores de Contenido",
    "who.artist": "Artistas y Músicos",
    "who.local": "Negocios Locales",
    "who.anyone": "Cualquiera Listo para Ejecutar",
    "who.warning": "Esto NO es para personas buscando atajos, fórmulas mágicas o éxito de la noche a la mañana. Si no estás listo para ejecutar, esto no es para ti.",

    // Founder / About Us
    "founder.label": "Sobre Nosotros",
    "founder.headline": "Nuestra Misión",
    "founder.headline2": "y Visión",
    
    // Mission
    "founder.mission.label": "Nuestra Misión",
    "founder.mission.title": "Construyendo Sistemas Reales de Visibilidad",
    "founder.mission.text": "En VISION DM, construimos sistemas reales de visibilidad para emprendedores, creadores y negocios listos para ejecutar. Nuestra misión es convertir ideas en impacto, consistencia en crecimiento, y contenido en resultados medibles — sin hype, atajos ni promesas vacías. No vendemos fama. Construimos sistemas que funcionan.",
    
    // Vision
    "founder.vision.label": "Nuestra Visión",
    "founder.vision.title": "Infraestructura para el Crecimiento",
    "founder.vision.text": "Nuestra visión es convertirnos en un ecosistema global de crecimiento impulsado por estructura, ejecución y claridad. Buscamos dar a personas alrededor del mundo una forma confiable de escalar su marca, alcance e ingresos a través de un sistema simple, repetible y basado en datos. VISION DM no es una agencia tradicional. Es infraestructura para el crecimiento.",
    
    // Founder Profile
    "founder.role": "Fundador y Arquitecto del Sistema",
    "founder.name": "Daniel Alejandro Mora",
    "founder.title": "Emprendedor Colombiano, Streamer y Fundador del Sistema DM",
    "founder.bio": "Más de 10 años de proceso no solo construyendo negocios, sino observando personas, patrones y comportamientos reales. Cada etapa —desde emprender joven, fracasar, migrar, empezar de cero y volver a crear— fortaleció una sola ventaja competitiva: la capacidad de pensar con claridad, leer contextos y convertir ideas en sistemas ejecutables.",
    "founder.bio2": "El verdadero poder no está en el talento ni en la suerte, sino en la mente que sabe crear, adaptar y repetir lo que funciona. De esa acumulación de experiencias reales nace el Sistema DM: una metodología diseñada para transformar intención en visibilidad, y visibilidad en crecimiento medible.",
    
    "founder.trust1": "Empresa Registrada en USA",
    "founder.trust2": "Identidad Real y Transparencia",
    "founder.trust3": "Metodología Probada",
    "founder.instagram": "Conectar",
    "founder.cta.book": "Agendar Llamada",

    // Plans
    "plans.label": "Membresía",
    "plans.headline": "Elige Tu",
    "plans.headline2": "Nivel de Crecimiento",
    "plans.intro": "Sistemas estructurados. Ejecución real. Visibilidad consistente.",
    "plans.level1": "Nivel 1",
    "plans.level1.subtitle": "Base",
    "plans.level1.desc": "Inicia con consistencia y una base sólida",
    "plans.level2": "Nivel 2",
    "plans.level2.subtitle": "Crecimiento",
    "plans.level2.desc": "Crece con seguimiento y mejora continua",
    "plans.level3": "Nivel 3",
    "plans.level3.subtitle": "Escala",
    "plans.level3.desc": "Control, claridad y crecimiento sostenido",
    "plans.level3.metric.ideas": "ideas de contenido",
    "plans.level3.platforms": "Facebook, Instagram, TikTok, YouTube",
    "plans.level3.feature.profile": "Análisis profundo de perfil y marca",
    "plans.level3.feature.positioning": "Posicionamiento estratégico claro",
    "plans.level3.feature.dataDriven": "Ejecución basada en datos y comportamiento",
    "plans.level3.feature.dmSystem": "Sistema DM personalizado a escala",
    "plans.level3.feature.ideas": "100 ideas mensuales con intención estratégica",
    "plans.level3.feature.indirectSales": "Venta indirecta (sin presión comercial)",
    "plans.level3.feature.organization": "Organización profesional de contenido",
    "plans.level3.feature.designResources": "30 recursos de diseño gráfico premium",
    "plans.level3.feature.nicheAnalysis": "Análisis de nicho y tendencias (nivel avanzado)",
    "plans.level3.feature.prioritySupport": "Soporte prioritario",
    "plans.level3.feature.weeklySessions": "Sesiones estratégicas semanales",
    "plans.level3.feature.optimization": "Optimización continua del sistema",
    "plans.cta": "Comenzar",
    "plans.feature.tasks": "tareas estructuradas mensuales",
    "plans.feature.videos": "videos base (máx 20s)",
    "plans.feature.publications": "publicaciones mensuales",
    "plans.feature.networks": "Facebook e Instagram",
    "plans.feature.logo.professional": "Diseño de logo profesional",
    "plans.feature.logo.premium": "Diseño de logo premium",
    "plans.feature.logo.brandkit": "Brand kit completo",
    "plans.feature.cover": "Recursos para redes sociales",
    "plans.feature.folder": "Carpeta de contenido organizada",
    "plans.feature.support.weekday": "Soporte en horario laboral",
    "plans.feature.support.24": "Soporte 24/7 prioritario",
    "plans.feature.controls": "controles personalizados mensuales",
    "plans.feature.strategy.monthly": "Sesión estratégica mensual",
    "plans.feature.strategy.weekly": "Sesiones estratégicas semanales",
    "plans.feature.profile.analysis": "Análisis profundo de perfil para identificar tu visión",
    "plans.feature.design.resources.15": "15 recursos adicionales de diseño gráfico",
    "plans.feature.design.resources.30": "30 recursos adicionales de diseño gráfico",
    "plans.feature.niche.analysis": "Análisis pro de nicho y tendencias",
    "plans.popular": "Más Popular",
    "plans.ideal": "Ideal para",
    "plans.platforms.label": "Plataformas",

    // Booking
    "booking.label": "Hablemos",
    "booking.headline": "Agenda una Llamada",
    "booking.headline2": "de Estrategia Personal",
    "booking.description": "¿Tienes preguntas? ¿Quieres discutir si esto es para ti? Agenda una llamada con nuestro equipo. Sin presión, sin trucos de venta—solo conversación honesta.",
    "booking.cta": "Agenda Tu Llamada",
    "booking.note": "Las llamadas son solo para consultas serias",

    // CTA
    "cta.headline": "Deja de Esperar.",
    "cta.headline2": "Empieza a Ejecutar.",
    "cta.description": "La visibilidad crea oportunidad. La oportunidad crea legado. Lo único entre tú y los resultados es la ejecución.",
    "cta.button": "Únete a VISION DM",
    "cta.secondary": "Empieza a Ejecutar Hoy",

    // Footer
    "footer.tagline": "Visibilidad. Ejecución. Legado.",
    "footer.rights": "Todos los derechos reservados.",
    "footer.company": "VISION DM LLC",
    "footer.legal": "Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.social": "Social",
    "footer.contact": "Contacto",

    // Privacy Policy
    "privacy.title": "Política de",
    "privacy.title2": "Privacidad",
    "privacy.updated": "Última actualización: 30 de enero de 2026",
    "privacy.intro": "En Vision DM LLC (\"Vision DM\", \"nosotros\"), respetamos tu privacidad. Esta Política explica cómo recopilamos, usamos y protegemos tu información cuando visitas nuestro sitio web, usas nuestros servicios o te comunicas con nosotros.",
    "privacy.s1.title": "1. Información que recopilamos",
    "privacy.s1.intro": "Podemos recopilar:",
    "privacy.s1.a.title": "a) Información que tú nos proporcionas",
    "privacy.s1.a.item1": "Nombre y apellido",
    "privacy.s1.a.item2": "Correo electrónico y/o número de teléfono",
    "privacy.s1.a.item3": "Datos de facturación (si aplica)",
    "privacy.s1.a.item4": "Mensajes y contenido que envías (formularios, chats, solicitudes, briefs creativos)",
    "privacy.s1.b.title": "b) Información recopilada automáticamente",
    "privacy.s1.b.item1": "Dirección IP aproximada, tipo de navegador, dispositivo, sistema operativo",
    "privacy.s1.b.item2": "Páginas visitadas, tiempo de navegación, enlaces y eventos (analytics)",
    "privacy.s1.b.item3": "Cookies y tecnologías similares (ver sección 6)",
    "privacy.s1.c.title": "c) Información de terceros (si aplica)",
    "privacy.s1.c.text": "Procesadores de pago, plataformas de agenda, herramientas de marketing o analítica, redes sociales cuando interactúas con nuestros perfiles o anuncios.",
    "privacy.s2.title": "2. Cómo usamos tu información",
    "privacy.s2.intro": "Usamos tu información para:",
    "privacy.s2.item1": "Responder solicitudes, cotizaciones y soporte",
    "privacy.s2.item2": "Prestar y mejorar nuestros servicios",
    "privacy.s2.item3": "Procesar pagos y prevenir fraude",
    "privacy.s2.item4": "Enviar comunicaciones (actualizaciones, confirmaciones, cambios del servicio)",
    "privacy.s2.item5": "Marketing (solo cuando sea permitido por ley o con tu consentimiento, según corresponda)",
    "privacy.s2.item6": "Cumplimiento legal y seguridad del sitio",
    "privacy.s3.title": "3. Base legal (si aplica)",
    "privacy.s3.intro": "Dependiendo de tu ubicación, procesamos datos con base en:",
    "privacy.s3.item1": "Ejecución de un contrato (prestación de servicios)",
    "privacy.s3.item2": "Interés legítimo (seguridad, mejoras, prevención de fraude)",
    "privacy.s3.item3": "Consentimiento (marketing, cookies no esenciales)",
    "privacy.s3.item4": "Obligaciones legales (impuestos, contabilidad)",
    "privacy.s4.title": "4. Cómo compartimos tu información",
    "privacy.s4.noSell": "No vendemos tu información personal.",
    "privacy.s4.intro": "Podemos compartirla con:",
    "privacy.s4.item1": "Proveedores que nos ayudan a operar (hosting, analítica, CRM, email, pagos)",
    "privacy.s4.item2": "Autoridades si es requerido por ley o para proteger derechos y seguridad",
    "privacy.s4.item3": "Transferencias de negocio (fusión, adquisición, reorganización)",
    "privacy.s4.note": "Todos los proveedores deben manejar la información conforme a esta Política y medidas razonables de seguridad.",
    "privacy.s5.title": "5. Retención de datos",
    "privacy.s5.intro": "Conservamos la información solo el tiempo necesario para:",
    "privacy.s5.item1": "Proveer el servicio",
    "privacy.s5.item2": "Cumplir obligaciones legales/contables",
    "privacy.s5.item3": "Resolver disputas y hacer cumplir acuerdos",
    "privacy.s6.title": "6. Cookies y tecnologías similares",
    "privacy.s6.intro": "Usamos cookies para:",
    "privacy.s6.item1": "Funcionamiento del sitio",
    "privacy.s6.item2": "Analítica y rendimiento",
    "privacy.s6.item3": "Marketing (si aplica)",
    "privacy.s6.note": "Puedes controlar cookies desde la configuración de tu navegador.",
    "privacy.s7.title": "7. Seguridad",
    "privacy.s7.text": "Implementamos medidas razonables (técnicas y organizativas) para proteger tu información. Aun así, ningún sistema es 100% seguro.",
    "privacy.s8.title": "8. Tus derechos y opciones",
    "privacy.s8.intro": "Según tu estado/país, puedes tener derecho a:",
    "privacy.s8.item1": "Acceder, corregir o eliminar tu información",
    "privacy.s8.item2": "Oponerte o limitar ciertos usos",
    "privacy.s8.item3": "Retirar consentimiento (cuando aplique)",
    "privacy.s8.contact": "Para ejercer derechos:",
    "privacy.s9.title": "9. Privacidad de menores",
    "privacy.s9.text": "Nuestros servicios no están dirigidos a menores de 13 años (o la edad mínima aplicable). Si crees que un menor nos envió datos, contáctanos para eliminarlo.",
    "privacy.s10.title": "10. Enlaces a terceros",
    "privacy.s10.text": "Nuestro sitio puede contener enlaces a terceros. No controlamos sus políticas. Revisa la privacidad de cada sitio.",
    "privacy.s11.title": "11. Cambios a esta Política",
    "privacy.s11.text": "Podemos actualizar esta Política. Publicaremos la nueva fecha de \"Última actualización\". Cambios importantes podrán comunicarse por email si corresponde.",
    "privacy.s12.title": "12. Contacto",
    "privacy.s12.email": "Correo:",

    // Terms of Service
    "terms.title": "Términos de",
    "terms.title2": "Servicio",
    "terms.updated": "Última actualización: 30 de enero de 2026",
    "terms.intro": "Estos Términos de Servicio (\"Términos\") rigen el uso del sitio web y los servicios ofrecidos por Vision DM LLC (\"Vision DM\", \"nosotros\"). Al acceder o usar el sitio, aceptas estos Términos.",
    "terms.s1.title": "1. Elegibilidad",
    "terms.s1.text": "Debes tener al menos 18 años (o la mayoría de edad en tu jurisdicción) para usar nuestros servicios, o contar con autorización de un adulto responsable.",
    "terms.s2.title": "2. Servicios",
    "terms.s2.text1": "Ofrecemos servicios creativos y digitales (por ejemplo: branding, diseño, edición, contenido, consultoría, optimización y productos relacionados), según lo publicado en el sitio o acordado por escrito.",
    "terms.s2.text2": "El alcance exacto, entregables, tiempos y precios se definen en:",
    "terms.s2.item1": "una propuesta / cotización,",
    "terms.s2.item2": "un contrato, o",
    "terms.s2.item3": "un acuerdo por escrito (incluye email o documento de proyecto).",
    "terms.s2.note": "Si existe conflicto entre estos Términos y un contrato específico, prevalece el contrato específico.",
    "terms.s3.title": "3. Pagos y facturación",
    "terms.s3.item1": "Los precios se muestran en USD (a menos que se indique lo contrario).",
    "terms.s3.item2": "Los pagos pueden ser por adelantado, por hitos o según el plan acordado.",
    "terms.s3.item3": "Si un pago no se realiza, podemos pausar entregas y soporte hasta regularizar.",
    "terms.s3.item4.label": "Cargos de terceros:",
    "terms.s3.item4.text": "Tu banco o pasarela puede cobrar comisiones; no las controlamos.",
    "terms.s4.title": "4. Reembolsos",
    "terms.s4.item1": "Por tratarse de servicios creativos y digitales, los reembolsos no son automáticos.",
    "terms.s4.item2": "Si el trabajo ya inició, los pagos pueden ser no reembolsables, total o parcialmente, según el avance y costos.",
    "terms.s4.item3": "Si aplica un reembolso o ajuste, se definirá caso por caso conforme al acuerdo.",
    "terms.s5.title": "5. Revisiones y cambios de alcance",
    "terms.s5.item1": "Incluimos rondas de revisiones por entregable (si no se define por contrato, asumimos 1–2 rondas razonables).",
    "terms.s5.item2": "Cambios fuera del alcance original (\"scope creep\") pueden requerir costo extra o ajuste de cronograma.",
    "terms.s6.title": "6. Responsabilidades del cliente",
    "terms.s6.intro": "Para cumplir plazos, el cliente debe:",
    "terms.s6.item1": "Entregar información y materiales necesarios (logos, fotos, accesos, brief, referencias)",
    "terms.s6.item2": "Responder en tiempos razonables",
    "terms.s6.item3": "Confirmar aprobaciones cuando se solicite",
    "terms.s6.note": "Retrasos del cliente pueden mover fechas de entrega.",
    "terms.s7.title": "7. Propiedad intelectual",
    "terms.s7.a.title": "a) Materiales del cliente",
    "terms.s7.a.text": "Siguen siendo del cliente. Nos autorizas a usarlos solo para realizar el proyecto.",
    "terms.s7.b.title": "b) Entregables finales",
    "terms.s7.b.text": "La propiedad/uso del entregable final se transfiere al cliente una vez recibido el pago completo, salvo que el contrato diga lo contrario.",
    "terms.s7.c.title": "c) Archivos editables / fuentes",
    "terms.s7.c.text": "La entrega de archivos editables (por ejemplo .PSD, .AI, proyectos) debe estar incluida explícitamente en el acuerdo. Si no, podemos entregar formatos finales (PNG/JPG/MP4/PDF, etc.).",
    "terms.s7.d.title": "d) Portfolio",
    "terms.s7.d.text": "Podemos mostrar el trabajo en nuestro portafolio/redes como caso de éxito, a menos que el cliente solicite por escrito confidencialidad o se acuerde NDA.",
    "terms.s8.title": "8. Uso del sitio",
    "terms.s8.intro": "Te comprometes a no:",
    "terms.s8.item1": "Usar el sitio para actividades ilegales o fraudulentas",
    "terms.s8.item2": "Intentar acceder a sistemas o cuentas sin autorización",
    "terms.s8.item3": "Copiar o redistribuir contenido del sitio sin permiso",
    "terms.s9.title": "9. Descargos de responsabilidad",
    "terms.s9.text": "El sitio y los servicios se proporcionan \"tal cual\". No garantizamos resultados específicos (por ejemplo, crecimiento, ventas, viralidad), ya que dependen de múltiples factores fuera de nuestro control (mercado, plataforma, presupuesto, consistencia, etc.).",
    "terms.s10.title": "10. Limitación de responsabilidad",
    "terms.s10.intro": "En la medida permitida por la ley, Vision DM no será responsable por:",
    "terms.s10.item1": "Pérdidas indirectas, incidentales, especiales o consecuentes",
    "terms.s10.item2": "Lucro cesante, pérdida de datos o reputación",
    "terms.s10.item3": "Fallas de terceros (plataformas, hosting, redes sociales, pasarelas)",
    "terms.s10.note": "Si aplica responsabilidad, se limita al monto pagado por el cliente en los últimos 90 días, o al proyecto específico, lo que sea menor.",
    "terms.s11.title": "11. Terminación",
    "terms.s11.intro": "Podemos terminar o suspender el acceso/servicio si:",
    "terms.s11.item1": "Hay incumplimiento de pagos",
    "terms.s11.item2": "Hay uso indebido del sitio",
    "terms.s11.item3": "Hay abuso, acoso o comportamiento inapropiado",
    "terms.s11.note": "El cliente también puede terminar según lo que indique el contrato. Los trabajos realizados hasta la fecha se facturan según avance.",
    "terms.s12.title": "12. Ley aplicable",
    "terms.s12.text1": "Estos Términos se rigen por las leyes del Estado de Utah, Estados Unidos, sin considerar conflictos de leyes.",
    "terms.s12.text2": "Jurisdicción: Salt Lake City, Utah.",
    "terms.s13.title": "13. Cambios a los Términos",
    "terms.s13.text": "Podemos actualizar los Términos. La fecha de \"Última actualización\" indicará cambios. El uso continuo del sitio implica aceptación de la versión vigente.",
    "terms.contact.title": "Contacto",
    "terms.contact.email": "Correo:",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
